#!/bin/bash
# Create gitignore templates for different project types

echo "Creating gitignore templates..."

# Create templates directory
mkdir -p ~/dev/tools/templates/gitignore

# Python .gitignore
cat > ~/dev/tools/templates/gitignore/python.gitignore << 'EOF'
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
.venv
pip-log.txt
pip-delete-this-directory.txt
.pytest_cache/
.coverage
.tox/
*.egg-info/
.mypy_cache/
.dmypy.json
dmypy.json
.pyre/
.ruff_cache/
EOF

# Node.js .gitignore
cat > ~/dev/tools/templates/gitignore/node.gitignore << 'EOF'
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.npm
.yarn-integrity
.env
.env.local
.env.*.local
.cache
dist/
build/
.parcel-cache
.next
.nuxt
.vuepress/dist
.serverless/
.fusebox/
.dynamodb/
.tern-port
.DS_Store
EOF

# Rust .gitignore
cat > ~/dev/tools/templates/gitignore/rust.gitignore << 'EOF'
# Generated by Cargo
/target/
Cargo.lock

# IDE files
.vscode/
.idea/
*.swp
*.swo

# OS generated files
.DS_Store
Thumbs.db
EOF

# Go .gitignore
cat > ~/dev/tools/templates/gitignore/go.gitignore << 'EOF'
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with `go test -c`
*.test

# Output of the go coverage tool
*.out

# Go workspace file
go.work
go.work.sum

# IDE files
.vscode/
.idea/
*.swp
*.swo
EOF

# General .gitignore
cat > ~/dev/tools/templates/gitignore/general.gitignore << 'EOF'
# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Editor files
.vscode/
.idea/
*.swp
*.swo
*~
.project
.classpath
.settings/

# Logs
logs/
*.log

# Runtime data
pids/
*.pid
*.seed
*.pid.lock

# Compiled files
*.com
*.class
*.dll
*.exe
*.o
*.so

# Temporary files
*.tmp
*.temp
tmp/
temp/
EOF

echo "Gitignore templates created in ~/dev/tools/templates/gitignore/"
echo ""
echo "Usage examples:"
echo "cp ~/dev/tools/templates/gitignore/python.gitignore .gitignore  # Python project"
echo "cp ~/dev/tools/templates/gitignore/node.gitignore .gitignore    # Node.js project"
echo "cat ~/dev/tools/templates/gitignore/general.gitignore >> .gitignore  # Add general rules"
